### ISSUE TITLE
Fish swim speed increases proportionally with Dave's swim speed (and a few other issues/nitpicks)

### ISSUE THREAD

**Issue by jupiter878lorem** [devopsdinosaur/dave-the-diver-mods#19]
-Most recent steam version with both DLC installed, and explicitly tested if there was another variable causing the issue. The "Diving - Speed Boost" option changes both fish and Dave's swim speed, with both becoming faster and slower.

-Requesting an option to exclude weapons, tools, and possibly some other things for the Diving - Auto-pickup: Items feature. More on the [Nexusmods](https://www.nexusmods.com/davethediver/mods/4?tab=posts&BH=0) post section, on the long reply to the comment of the same topic.

-Lag issues. When controlling the "Diving - Auto-pickup: Radius" option, there were no issues, even above 30. (while crab pots started to not get applied automatically at values 60 and above, this seemed like a reasonable limit caused by overload) However, turning up the "Diving - Toxic Aura: Radius" option caused noticeable lag, even at a value of 1, and significantly decreased fps at values of 3 or higher; it was especially noticeable at the top half of the blue hole(the part containing the shallows, medium depth, and depths), and lessened in small sub-areas separated by doors and transition points(such as the part under the sunken ship), but the number of fish onscreen or near me did not seem to matter. If possible, an option to change the rate at which the toxic/sleep 'pulse' activates would be extremely helpful; a wider area that activates less frequently would make it much easier for me to retrieve fish hiding in corners.

-When the infinite crab pot option is on, the caught crabs seem to mostly be the lowest quality (one star), which is normally caused by providing [low rank fish as bait](https://www.reddit.com/r/DavetheDiverOfficial/comments/18sjgok/crab_lobster_trap_bait_rank_and_stars_quality/). I used to start fishing from the lowest areas and tried to supply all crab traps with the highest quality fish (rank [8](https://dave-the-diver.fandom.com/wiki/Capelin) or [9](https://dave-the-diver.fandom.com/wiki/Waptia_Fieldensis)), and I hope that the auto-trap feature also allows to simulate high rank bait and good rewards.

**Comment by devopsdinosaur** [comment]
This is perfect @jupiter878lorem ; thank you very much!  I did notice the lag but had not gotten around to narrowing down from where it was stemming, so I really appreciate the testing effort.  As for the crab traps, I had no idea the stuff they were catching was low quality.  I should be able to fix that easily.  Thanks again! -- dd

**Comment by mishrasumitranjan** [comment]
I noticed the lag as well and disbled the auto pick-up options. While wondering if there was another option to streamline it more, an idea came to mind. When close to a pickable object the button prompt for space appears, if this can be tracked and checked, then only the button press needs to be automated for this. This would reduce the range to the game's original range, but would probably help with the lag, as the script would no longer be checking a radius.

**Comment by devopsdinosaur** [comment]
All but the item exclusion stuff should be fixed in v0.0.9.  Let me know if you're still having issues.

**Comment by jupiter878lorem** [comment]
All features are working perfectly! There is still a tiny lag-spike whenever the pulse goes off, but now that I've increased its interval, it's much better than before. I'm wondering if @mishrasumitranjan 's idea could be implemented as an additional option, though I'm also satisfied with the current way of having just a massive range.

In regards to the the hittable update, the [pickaxe](https://dave-the-diver.fandom.com/wiki/Pickaxe) is not only capable of getting the harder ores at the depths and so on, but also doubles the output of ores found above (iron, lead, and copper). The [eco bracelet](https://dave-the-diver.fandom.com/wiki/Charms) from one of the ecowatcher task rewards also gives an additional ore piece per ore node. Meanwhile, the [bladderwrack dumplings](https://dave-the-diver.fandom.com/wiki/Mima%27s_Restaurant) found at Mima's restaurant also seems to nearly double the output of underwater plants (when diving, not at the seapeople farm) when hit, during the diving session when it has been eaten. It would be nice if you could include these multipliers into the auto-hitting feature, or better yet, have a controllable multiplier/extra item probability (as I don't really know the exact numbers for either the pickaxe or the dumplings)

Also, do you happen to have a patreon or ko-fi account by chance? At this point you've done more stuff than a paid trainer subscription does, and it would be nice if I could donate to you for your efforts somehow, even a one-time donation.

**Comment by devopsdinosaur** [comment]
Yup, my Kofi page is [https://ko-fi.com/devopsdinosaur/](url) but you don't have to feel obligated to tip anything--I do this mostly for fun.  

The item pickup differentiation stuff is just about working and should be ready for release by the end of the weekend.

**Comment by devopsdinosaur** [comment]
All of your original requests should be covered in 0.0.11 just uploaded.  Gonna close this ticket and open one for the hittable stuff (and add your comment).  Thanks again!  Let me know what you think about the auto-pickup-items.txt file and if I missed stuff. -- dd
